usage: Avoid "no method 'codespan'" error
With Markdown-style `code` markup, I was getting:

  $ dat help
  /.../dat/node_modules/ansimd/node_modules/marked/lib/marked.js:1209
      throw e;
            ^
  TypeError: Object #<Object> has no method 'codespan'
  Please report this to https://github.com/chjj/marked.
      at InlineLexer.output (/.../dat/node_modules/ansimd/node_modules/marked/lib/marked.js:660:28)
      at Parser.tok (/.../dat/node_modules/ansimd/node_modules/marked/lib/marked.js:1064:50)
      at Parser.parse (/.../dat/node_modules/ansimd/node_modules/marked/lib/marked.js:924:17)
      at Function.Parser.parse (/.../dat/node_modules/ansimd/node_modules/marked/lib/marked.js:911:17)
      at marked (/.../dat/node_modules/ansimd/node_modules/marked/lib/marked.js:1201:19)
      at render (/.../dat/node_modules/ansimd/index.js:21:13)
      at Object.dat.help (/.../dat/lib/commands.js:166:15)
      at ready (/.../dat/cli.js:60:35)
      at /.../dat/index.js:105:32
      at /.../dat/lib/commands.js:654:25

Avoid that by using a code block for the syntax declaration.  It looks
like the current release of marked (which we pull in via ansimd) is
indeed missing code spans [1].

[1]: https://github.com/chjj/marked/blob/v0.3.2/README.md#inline-level-renderer-methods